### PR TITLE
Rename java package to io.jaegertracing

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to https://github.com/jaegertracing/jaeger-client-java/issues/287

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
the old `com.uber.jaeger:jaeger-thrift` will be still published it will be a wrapper around `io.jaegertracing`

**Comment by pavolloffay** [comment]
Let's wait with merge until the whole concept in java client is in place.

**Comment by pavolloffay** [comment]
ok it has been merged anyway :)

**Comment by yurishkuro** [comment]
> ok it has been merged anyway :)

yeah, sorry  :-)

as I mentioned above, I think it's ok to merge since each repo opts in for specific commit of the idl submodule, so there's no immediate impact, and we can safely upgrade Java repo to use renamed package because we consider thrift files as internal implementation details.

**Comment by yurishkuro** [comment]
NB - Zipkin doesn't even have dependency on thrift directly, Adrian implemented serialization manually, and it didn't look too bad.

**Pull request merged**
