### PR TITLE
Update proto for marshal issue

### PR DESCRIPTION
**Pull request by rim99**
## Which problem is this PR solving?
Resolves #4150

## Description of the changes
- Make sure time fields works normally in generated go file 

## How was this change tested?
- Tested with PR https://github.com/jaegertracing/jaeger/pull/6159

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
What does "works normally" mean? What wasn't working?

**Comment by rim99** [comment]
@yurishkuro Before this change, this test would fail
https://github.com/rim99/jaeger/blob/d00b4d3888475cb86668849b75246616fe3cb389/cmd/query/app/apiv3/grpc_handler_test.go#L81

It seems, server side cannot receive time values in request, and initialized these as 0001-01-01T00:00:00Z

**Comment by yurishkuro** [comment]
> Before this change, this test would fail

I don't follow. The test is running in the main repo, against the official proto. What specifically makes it fail?

**Comment by rim99** [comment]
@yurishkuro Removed gogoproto lines in proto file. Kind feel this should be the correct direction to move, since gogoproto project is already deprecated. Ans also to keep align with rest of lines.

**Comment by yurishkuro** [comment]
Why can't we do it as in these PRs?
  * https://github.com/jaegertracing/jaeger-idl/pull/109
  * https://github.com/jaegertracing/jaeger/pull/6218

**Comment by rim99** [comment]
Tried with your latest merge. The go test would still fail

```
Running tool: /usr/bin/go test -timeout 30s -run ^TestGetTraceWithTimeWindow$ github.com/jaegertracing/jaeger/cmd/query/app/apiv3

=== RUN   TestGetTraceWithTimeWindow
    /home/xxx/projects/go/jaeger/cmd/query/app/apiv3/grpc_handler_test.go:140:
                Error Trace:    /home/xxx/projects/go/jaeger/cmd/query/app/apiv3/grpc_handler_test.go:140
                Error:          Received unexpected error:
                                rpc error: code = Internal desc = grpc: error while marshaling: proto: time.Time does not implement Marshal
                Test:           TestGetTraceWithTimeWindow
--- FAIL: TestGetTraceWithTimeWindow (0.00s)
FAIL
FAIL    github.com/jaegertracing/jaeger/cmd/query/app/apiv3     0.008s
```

**Comment by yurishkuro** [comment]
> Running tool: /usr/bin/go test -timeout 30s -run ^TestGetTraceWithTimeWindow$ github.com/jaegertracing/jaeger/cmd/query/app/apiv3

Please create a PR that demonstrates the test failure (without any other change)

**Comment by rim99** [comment]
> > Running tool: /usr/bin/go test -timeout 30s -run ^TestGetTraceWithTimeWindow$ github.com/jaegertracing/jaeger/cmd/query/app/apiv3
> 
> Please create a PR that demonstrates the test failure (without any other change)

Please check this draft PR: https://github.com/jaegertracing/jaeger/pull/6228

**Comment by rim99** [comment]
No change

**Pull request closed without merging**
